/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author pooya
 */
public class game extends javax.swing.JFrame {
int[]a={1,2,3,4,5,6,1,2,3,4,5,6};
int first=0;
int count=0;
javax.swing.JButton p;
    /**
     * Creates new form game
     */
    public game() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b0 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        g = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b0.setBackground(new java.awt.Color(102, 255, 204));
        b0.setText("*");
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        b3.setBackground(new java.awt.Color(102, 255, 204));
        b3.setText("*");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.setBackground(new java.awt.Color(102, 255, 204));
        b4.setText("*");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b9.setBackground(new java.awt.Color(102, 255, 204));
        b9.setText("*");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b1.setBackground(new java.awt.Color(102, 255, 204));
        b1.setText("*");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setBackground(new java.awt.Color(102, 255, 204));
        b2.setText("*");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b6.setBackground(new java.awt.Color(102, 255, 204));
        b6.setText("*");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b5.setBackground(new java.awt.Color(102, 255, 204));
        b5.setText("*");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b8.setBackground(new java.awt.Color(102, 255, 204));
        b8.setText("*");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b7.setBackground(new java.awt.Color(102, 255, 204));
        b7.setText("*");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b10.setBackground(new java.awt.Color(102, 255, 204));
        b10.setText("*");
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });

        b11.setBackground(new java.awt.Color(102, 255, 204));
        b11.setText("*");
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });

        g.setBackground(new java.awt.Color(204, 51, 0));
        g.setText("بازی جدید");
        g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b11))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(b3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(b0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b2))
                    .addComponent(g, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b0)
                    .addComponent(b1)
                    .addComponent(b2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b3)
                    .addComponent(b5)
                    .addComponent(b4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b6)
                    .addComponent(b8)
                    .addComponent(b7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b9)
                    .addComponent(b10)
                    .addComponent(b11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(g)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gActionPerformed
        // TODO add your handling code here:
        count=0;
        b0.setText("*");b1.setText("*");b2.setText("*");
        b3.setText("*");b4.setText("*");b5.setText("*");
        b6.setText("*");b7.setText("*");b8.setText("*");
        b9.setText("*");b10.setText("*");b11.setText("*");
        b0.setEnabled(true);b1.setEnabled(true);b2.setEnabled(true);
        b3.setEnabled(true);b4.setEnabled(true);b5.setEnabled(true);
        b6.setEnabled(true);b7.setEnabled(true);b8.setEnabled(true);
        b9.setEnabled(true);b10.setEnabled(true);b11.setEnabled(true);
        int k;
        for(int i=0;i<12;i++){
            k=2;
            while(k>=2){
                k=0;
                a[i]=(int)(((Math.random())*6)+1);
                for(int j=0;j<i;j++)
                    if(a[i]==a[j])
                        k++;
            }
        }
        first=0;
    }//GEN-LAST:event_gActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        // TODO add your handling code here:
        int i=0;
        javax.swing.JButton c=b0;
        if(first==a[i] && p==c)
            return;
        if(first==0){
            first=a[i];
            p=c;
            c.setText(""+a[i]);
            return;
        }
        if(first==a[i]){
            c.setText(""+a[i]);
            p.setEnabled(false);
            c.setEnabled(false);
            first=0;
            p=null;
            count++;
            if(count==6)
                g.doClick();
        }    
        else{
            p.setText("*");
            c.setText(""+a[i]);
            first=a[i];
            p=c;
        }    
    }//GEN-LAST:event_b0ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        int i=1;
        javax.swing.JButton c=b1;
        if(first==a[i] && p==c)
            return;
        if(first==0){
            first=a[i];
            p=c;
            c.setText(""+a[i]);
            return;
        }
        if(first==a[i]){
            c.setText(""+a[i]);
            p.setEnabled(false);
            c.setEnabled(false);
            first=0;
            p=null;
            count++;
            if(count==6)
                g.doClick();
        }    
        else{
            p.setText("*");
            c.setText(""+a[i]);
            first=a[i];
            p=c;
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        int i=2;
        javax.swing.JButton c=b2;
        if(first==a[i] && p==c)
            return;
        if(first==0){
            first=a[i];
            p=c;
            c.setText(""+a[i]);
            return;
        }
        if(first==a[i]){
            c.setText(""+a[i]);
            p.setEnabled(false);
            c.setEnabled(false);
            first=0;
            p=null;
            count++;
            if(count==6)
                g.doClick();
        }    
        else{
            p.setText("*");
            c.setText(""+a[i]);
            first=a[i];
            p=c;
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        int i=3;
        javax.swing.JButton c=b3;
        if(first==a[i] && p==c)
            return;
        if(first==0){
            first=a[i];
            p=c;
            c.setText(""+a[i]);
            return;
        }
        if(first==a[i]){
            c.setText(""+a[i]);
            p.setEnabled(false);
            c.setEnabled(false);
            first=0;
            p=null;
            count++;
            if(count==6)
                g.doClick();
        }    
        else{
            p.setText("*");
            c.setText(""+a[i]);
            first=a[i];
            p=c;
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        int i=4;
        javax.swing.JButton c=b4;
        if(first==a[i] && p==c)
            return;
        if(first==0){
            first=a[i];
            p=c;
            c.setText(""+a[i]);
            return;
        }
        if(first==a[i]){
            c.setText(""+a[i]);
            p.setEnabled(false);
            c.setEnabled(false);
            first=0;
            p=null;
            count++;
            if(count==6)
                g.doClick();
        }    
        else{
            p.setText("*");
            c.setText(""+a[i]);
            first=a[i];
            p=c;
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        int i=5;
        javax.swing.JButton c=b5;
        if(first==a[i] && p==c)
            return;
        if(first==0){
            first=a[i];
            p=c;
            c.setText(""+a[i]);
            return;
        }
        if(first==a[i]){
            c.setText(""+a[i]);
            p.setEnabled(false);
            c.setEnabled(false);
            first=0;
            p=null;
            count++;
            if(count==6)
                g.doClick();
        }    
        else{
            p.setText("*");
            c.setText(""+a[i]);
            first=a[i];
            p=c;
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        int i=6;
        javax.swing.JButton c=b6;
        if(first==a[i] && p==c)
            return;
        if(first==0){
            first=a[i];
            p=c;
            c.setText(""+a[i]);
            return;
        }
        if(first==a[i]){
            c.setText(""+a[i]);
            p.setEnabled(false);
            c.setEnabled(false);
            first=0;
            p=null;
            count++;
            if(count==6)
                g.doClick();
        }    
        else{
            p.setText("*");
            c.setText(""+a[i]);
            first=a[i];
            p=c;
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        int i=7;
        javax.swing.JButton c=b7;
        if(first==a[i] && p==c)
            return;
        if(first==0){
            first=a[i];
            p=c;
            c.setText(""+a[i]);
            return;
        }
        if(first==a[i]){
            c.setText(""+a[i]);
            p.setEnabled(false);
            c.setEnabled(false);
            first=0;
            p=null;
            count++;
            if(count==6)
                g.doClick();
        }    
        else{
            p.setText("*");
            c.setText(""+a[i]);
            first=a[i];
            p=c;
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        int i=8;
        javax.swing.JButton c=b8;
        if(first==a[i] && p==c)
            return;
        if(first==0){
            first=a[i];
            p=c;
            c.setText(""+a[i]);
            return;
        }
        if(first==a[i]){
            c.setText(""+a[i]);
            p.setEnabled(false);
            c.setEnabled(false);
            first=0;
            p=null;
            count++;
            if(count==6)
                g.doClick();
        }    
        else{
            p.setText("*");
            c.setText(""+a[i]);
            first=a[i];
            p=c;
        }
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
        int i=9;
        javax.swing.JButton c=b9;
        if(first==a[i] && p==c)
            return;
        if(first==0){
            first=a[i];
            p=c;
            c.setText(""+a[i]);
            return;
        }
        if(first==a[i]){
            c.setText(""+a[i]);
            p.setEnabled(false);
            c.setEnabled(false);
            first=0;
            p=null;
            count++;
            if(count==6)
                g.doClick();
        }    
        else{
            p.setText("*");
            c.setText(""+a[i]);
            first=a[i];
            p=c;
        }
    }//GEN-LAST:event_b9ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
        // TODO add your handling code here:
        int i=10;
        javax.swing.JButton c=b10;
        if(first==a[i] && p==c)
            return;
        if(first==0){
            first=a[i];
            p=c;
            c.setText(""+a[i]);
            return;
        }
        if(first==a[i]){
            c.setText(""+a[i]);
            p.setEnabled(false);
            c.setEnabled(false);
            first=0;
            p=null;
            count++;
            if(count==6)
                g.doClick();
        }    
        else{
            p.setText("*");
            c.setText(""+a[i]);
            first=a[i];
            p=c;
        }
    }//GEN-LAST:event_b10ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
        // TODO add your handling code here:
        int i=11;
        javax.swing.JButton c=b11;
        if(first==a[i] && p==c)
            return;
        if(first==0){
            first=a[i];
            p=c;
            c.setText(""+a[i]);
            return;
        }
        if(first==a[i]){
            c.setText(""+a[i]);
            p.setEnabled(false);
            c.setEnabled(false);
            first=0;
            p=null;
            count++;
            if(count==6)
                g.doClick();
        }    
        else{
            p.setText("*");
            c.setText(""+a[i]);
            first=a[i];
            p=c;
        }
    }//GEN-LAST:event_b11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton g;
    // End of variables declaration//GEN-END:variables
}
